# Environment for installing Mindboggle
#
# This environment is configured for circleci.com continuous integration
# (testing).
#
# Authors:
#    - Arno Klein, 2016-2017  (arno@mindboggle.info)  http://binarybottle.com
#
# Copyright 2016-2017,  Mindboggle team (mindboggle.info), Apache v2.0 License

#-----------------------------------------------------------------------------
# mindboggle-env environment:
#-----------------------------------------------------------------------------
name: mindboggle-env
#-----------------------------------------------------------------------------
# mindboggle dependencies:
#-----------------------------------------------------------------------------
dependencies:
    - python>=3.5.1
    - vtk>=7.0
    - mesalib
    - matplotlib
    - numpy
    - scipy
    - pandas
    - cmake
    - pip
    - pip:
        - nibabel
        - nipype
        - prov
        - traits
        - xvfbwrapper
        - colormath
        - pydotplus

    - networkx
    - lxml
    - simplejson
    - future
    - nose
    #-------------------------------------------------------------------------
    # additional testing tools:
    #-------------------------------------------------------------------------
    - ipython
    - pytest
    - coverage

